#!/usr/bin/env python3
"""
Generate instruments registry JSON for Article_Eater v1.
Includes 50 instruments across affect, cognitive, and physiological domains.
"""

import json
from datetime import datetime, timezone

def create_registry():
    """Create and return the instruments registry."""

    instruments = [
        # AFFECT DOMAIN (21 instruments)
        {
            "instrument_id": "STAI",
            "full_name": "State-Trait Anxiety Inventory",
            "abbreviation": "STAI",
            "authors": "Spielberger, C. D., Gorsuch, R. L., Lushene, R., Vagg, P. R., & Jacobs, G. A.",
            "year": 1983,
            "reference_apa": "Spielberger, C. D. (1983). State-Trait Anxiety Inventory (STAI). Consulting Psychologists Press.",
            "doi": None,
            "approx_citations": 85000,
            "description": "40-item self-report measure of state and trait anxiety. Respondents rate items on 4-point scales regarding presence of anxiety symptoms and worry.",
            "type": "self_report",
            "items_count": 40,
            "administration_minutes": 10,
            "psychometrics": {
                "internal_consistency_alpha": "0.86-0.95",
                "test_retest_reliability": "0.73-0.86 (trait)",
                "validity_notes": "Strong convergent and discriminant validity. Extensively validated across populations."
            },
            "strengths": ["Highly cited and validated", "Separate state and trait measures", "Brief administration"],
            "weaknesses": ["Can be repetitive for respondents", "Some items redundant", "Ceiling effects possible"],
            "newer_alternatives": [{"instrument_id": "GAD-7", "reason": "Briefer assessment of anxiety"}],
            "domains": ["affect.anxiety"],
            "status": "active"
        },
        {
            "instrument_id": "GAD-7",
            "full_name": "Generalized Anxiety Disorder-7",
            "abbreviation": "GAD-7",
            "authors": "Spitzer, R. L., Kroenke, K., Williams, J. B., & Löwe, B.",
            "year": 2006,
            "reference_apa": "Spitzer, R. L., Kroenke, K., Williams, J. B., & Löwe, B. (2006). A brief measure for assessing generalized anxiety disorder. Archives of Internal Medicine, 166(10), 1092-1097.",
            "doi": "10.1001/archinte.166.10.1092",
            "approx_citations": 45000,
            "description": "7-item self-report screening tool for generalized anxiety disorder. Rapid assessment in clinical and research settings.",
            "type": "self_report",
            "items_count": 7,
            "administration_minutes": 2,
            "psychometrics": {
                "internal_consistency_alpha": "0.92",
                "test_retest_reliability": "0.83",
                "validity_notes": "High sensitivity (0.89) and specificity (0.97) for GAD diagnosis."
            },
            "strengths": ["Very brief", "Easy to administer", "Good diagnostic utility"],
            "weaknesses": ["Limited to GAD constructs", "May miss subtle anxiety features"],
            "newer_alternatives": [],
            "domains": ["affect.anxiety"],
            "status": "active"
        },
        {
            "instrument_id": "DASS-21",
            "full_name": "Depression Anxiety Stress Scales-21",
            "abbreviation": "DASS-21",
            "authors": "Lovibond, S. H., & Lovibond, P. F.",
            "year": 1995,
            "reference_apa": "Lovibond, S. H., & Lovibond, P. F. (1995). Manual for the Depression Anxiety Stress Scales (2nd ed.). Psychology Foundation of Australia.",
            "doi": None,
            "approx_citations": 15000,
            "description": "21-item self-report measure of depression, anxiety, and stress. Three subscales (7 items each) assess negative emotional states.",
            "type": "self_report",
            "items_count": 21,
            "administration_minutes": 5,
            "psychometrics": {
                "internal_consistency_alpha": "0.81-0.89",
                "test_retest_reliability": "0.71-0.81",
                "validity_notes": "Good discriminant validity across subscales."
            },
            "strengths": ["Brief version of DASS-42", "Three distinct constructs", "Transdiagnostic approach"],
            "weaknesses": ["Australian normative sample", "Less extensive research than STAI"],
            "newer_alternatives": [],
            "domains": ["affect.anxiety", "affect.depression", "affect.stress"],
            "status": "active"
        },
        {
            "instrument_id": "PANAS",
            "full_name": "Positive and Negative Affect Schedule",
            "abbreviation": "PANAS",
            "authors": "Watson, D., Clark, L. A., & Tellegen, A.",
            "year": 1988,
            "reference_apa": "Watson, D., Clark, L. A., & Tellegen, A. (1988). Development and validation of brief measures of positive and negative affect. Journal of Personality and Social Psychology, 54(6), 1063-1070.",
            "doi": "10.1037/0022-3514.54.6.1063",
            "approx_citations": 32000,
            "description": "20-item self-report of positive and negative affective states. Two 10-item subscales assess momentary emotional experience.",
            "type": "self_report",
            "items_count": 20,
            "administration_minutes": 3,
            "psychometrics": {
                "internal_consistency_alpha": "0.86-0.90",
                "test_retest_reliability": "0.47-0.68 (varies by time frame)",
                "validity_notes": "Well-established factor structure for positive and negative affect."
            },
            "strengths": ["Widely used in emotion research", "Orthogonal dimensions", "Brief and efficient"],
            "weaknesses": ["Limited to discrete emotions", "Momentary assessment only"],
            "newer_alternatives": [],
            "domains": ["affect.positive", "affect.negative"],
            "status": "active"
        },
        {
            "instrument_id": "SAM",
            "full_name": "Self-Assessment Manikin",
            "abbreviation": "SAM",
            "authors": "Bradley, M. M., & Lang, P. J.",
            "year": 1994,
            "reference_apa": "Bradley, M. M., & Lang, P. J. (1994). Measuring emotion. Journal of Behavior Therapy and Experimental Psychiatry, 25(1), 49-59.",
            "doi": "10.1016/0005-7916(94)90063-9",
            "approx_citations": 12000,
            "description": "Non-verbal pictorial scale assessing valence, arousal, and dominance in response to stimuli. Graphical manikin figures represent emotional dimensions.",
            "type": "observational_pictorial",
            "items_count": 3,
            "administration_minutes": 1,
            "psychometrics": {
                "internal_consistency_alpha": "0.76-0.87",
                "test_retest_reliability": "varies",
                "validity_notes": "Good convergent validity with physiological measures of arousal."
            },
            "strengths": ["Language-independent", "Rapid assessment", "Intuitive response format"],
            "weaknesses": ["Limited dimensional scope", "Cultural variations in interpretation"],
            "newer_alternatives": [],
            "domains": ["affect.valence", "affect.arousal"],
            "status": "active"
        },
        {
            "instrument_id": "POMS",
            "full_name": "Profile of Mood States",
            "abbreviation": "POMS",
            "authors": "McNair, D. M., Lorr, M., & Droppleman, L. F.",
            "year": 1971,
            "reference_apa": "McNair, D. M., Lorr, M., & Droppleman, L. F. (1971). Manual for the Profile of Mood States. Educational and Industrial Testing Service.",
            "doi": None,
            "approx_citations": 18000,
            "description": "65-item self-report of mood across six dimensions: tension, depression, anger, vigor, fatigue, confusion.",
            "type": "self_report",
            "items_count": 65,
            "administration_minutes": 8,
            "psychometrics": {
                "internal_consistency_alpha": "0.74-0.90",
                "test_retest_reliability": "0.57-0.67",
                "validity_notes": "Well-validated across clinical and non-clinical populations."
            },
            "strengths": ["Comprehensive mood assessment", "Multiple subscales", "Established norms"],
            "weaknesses": ["Lengthy administration", "Some item redundancy"],
            "newer_alternatives": [{"instrument_id": "POMS-SF", "reason": "Shorter 37-item version available"}],
            "domains": ["affect.mood"],
            "status": "active"
        },
        {
            "instrument_id": "PSS-10",
            "full_name": "Perceived Stress Scale-10",
            "abbreviation": "PSS-10",
            "authors": "Cohen, S., Kamarck, T., & Mermelstein, R.",
            "year": 1983,
            "reference_apa": "Cohen, S., Kamarck, T., & Mermelstein, R. (1983). A global measure of perceived stress. Journal of Health and Social Behavior, 24(4), 385-396.",
            "doi": "10.2307/2136404",
            "approx_citations": 35000,
            "description": "10-item self-report of perceived stress over past month. Assesses degree to which situations feel uncontrollable and overwhelming.",
            "type": "self_report",
            "items_count": 10,
            "administration_minutes": 3,
            "psychometrics": {
                "internal_consistency_alpha": "0.78",
                "test_retest_reliability": "0.85 (2 days), 0.55 (6 weeks)",
                "validity_notes": "Good convergent validity with health outcomes."
            },
            "strengths": ["Brief and efficient", "Wide applicability", "Predictive of health outcomes"],
            "weaknesses": ["Single dimension", "Subjective self-appraisal only"],
            "newer_alternatives": [],
            "domains": ["affect.stress"],
            "status": "active"
        },
        {
            "instrument_id": "VAS",
            "full_name": "Visual Analog Scale",
            "abbreviation": "VAS",
            "authors": "Wewers, M. E., & Lowe, N. K.",
            "year": 1990,
            "reference_apa": "Wewers, M. E., & Lowe, N. K. (1990). A critical review of visual analogue scale (VAS) for the measurement of clinical phenomena. Research in Nursing and Health, 13(4), 227-236.",
            "doi": "10.1002/nur.4770130405",
            "approx_citations": 8000,
            "description": "Generic continuous scale (typically 0-100mm or 0-10) for rating affective or pain states. Flexible for various constructs.",
            "type": "self_report",
            "items_count": 1,
            "administration_minutes": 1,
            "psychometrics": {
                "internal_consistency_alpha": "N/A (single item)",
                "test_retest_reliability": "varies by construct",
                "validity_notes": "Validity depends on specific application and anchors."
            },
            "strengths": ["Highly flexible", "Minimal cognitive load", "Continuous measurement"],
            "weaknesses": ["Abstract endpoints", "Scoring variability", "Limited contextual anchors"],
            "newer_alternatives": [],
            "domains": ["affect.generic"],
            "status": "active"
        },
        {
            "instrument_id": "PRS",
            "full_name": "Perceived Restorativeness Scale",
            "abbreviation": "PRS",
            "authors": "Hartig, T., Korpela, K., Evans, G. W., & Gärling, T.",
            "year": 1997,
            "reference_apa": "Hartig, T., Korpela, K., Evans, G. W., & Gärling, T. (1997). A measure of restorative quality in environments. Scandinavian Housing and Planning Research, 14(4), 175-194.",
            "doi": "10.1080/02815739708730435",
            "approx_citations": 3500,
            "description": "26-item self-report measuring perceived restorative qualities of environments. Four subscales: being away, fascination, coherence, scope.",
            "type": "self_report",
            "items_count": 26,
            "administration_minutes": 5,
            "psychometrics": {
                "internal_consistency_alpha": "0.82-0.88",
                "test_retest_reliability": "0.75-0.82",
                "validity_notes": "Correlates with attention restoration theory predictions."
            },
            "strengths": ["Environment-specific", "Theoretically grounded (ART)", "Multidimensional"],
            "weaknesses": ["Moderate length", "Specialized application"],
            "newer_alternatives": [],
            "domains": ["affect.restoration"],
            "status": "active"
        },
        {
            "instrument_id": "ROS",
            "full_name": "Restorative Outcomes Scale",
            "abbreviation": "ROS",
            "authors": "Korpela, K. M., & Hartig, T.",
            "year": 2008,
            "reference_apa": "Korpela, K. M., & Hartig, T. (2008). Restorative quality of favorite places. Journal of Environmental Psychology, 28(2), 157-165.",
            "doi": "10.1016/j.jenvp.2007.10.001",
            "approx_citations": 1200,
            "description": "7-item self-report of perceived restorative outcomes from environments. Shorter alternative to PRS focusing on restoration perceptions.",
            "type": "self_report",
            "items_count": 7,
            "administration_minutes": 2,
            "psychometrics": {
                "internal_consistency_alpha": "0.83",
                "test_retest_reliability": "varies",
                "validity_notes": "Efficient brief measure with good psychometric properties."
            },
            "strengths": ["Very brief", "Simple administration", "Environment-specific"],
            "weaknesses": ["Limited subscales", "Newer measure with less validation"],
            "newer_alternatives": [],
            "domains": ["affect.restoration"],
            "status": "active"
        },
        {
            "instrument_id": "SHS",
            "full_name": "Subjective Happiness Scale",
            "abbreviation": "SHS",
            "authors": "Lyubomirsky, S., & Lepper, H. S.",
            "year": 1999,
            "reference_apa": "Lyubomirsky, S., & Lepper, H. S. (1999). A measure of subjective happiness. Journal of Personality Assessment, 72(2), 169-194.",
            "doi": "10.1207/s15327752jpa7202_3",
            "approx_citations": 5000,
            "description": "4-item self-report of overall happiness and life satisfaction. Direct assessment of subjective well-being.",
            "type": "self_report",
            "items_count": 4,
            "administration_minutes": 1,
            "psychometrics": {
                "internal_consistency_alpha": "0.79-0.94",
                "test_retest_reliability": "0.71-0.73",
                "validity_notes": "Valid across cultures and populations."
            },
            "strengths": ["Extremely brief", "Direct happiness measure", "Cross-culturally validated"],
            "weaknesses": ["Overly simple for some contexts", "Limited construct breadth"],
            "newer_alternatives": [],
            "domains": ["affect.happiness"],
            "status": "active"
        },
        {
            "instrument_id": "AWE-S",
            "full_name": "Awe Experience Scale",
            "abbreviation": "AWE-S",
            "authors": "Yaden, D. B., Iwry, J., Slack, K. J., Eichstaedt, J. C., Zhao, Y., Vaillant, G. E., & Newberg, A. B.",
            "year": 2019,
            "reference_apa": "Yaden, D. B., Iwry, J., Slack, K. J., et al. (2019). The Awe Experience Scale. Journal of Positive Psychology, 14(4), 474-488.",
            "doi": "10.1080/17439760.2018.1519018",
            "approx_citations": 600,
            "description": "12-item self-report measuring awe responses to stimuli or environments. Captures vastness, accommodation, and affect dimensions.",
            "type": "self_report",
            "items_count": 12,
            "administration_minutes": 2,
            "psychometrics": {
                "internal_consistency_alpha": "0.87",
                "test_retest_reliability": "varies",
                "validity_notes": "New measure with emerging empirical support."
            },
            "strengths": ["Emotion-specific (awe)", "Recent development", "Efficient length"],
            "weaknesses": ["Limited empirical history", "Newer instrument"],
            "newer_alternatives": [],
            "domains": ["affect.awe"],
            "status": "active"
        },
        {
            "instrument_id": "FACS",
            "full_name": "Facial Action Coding System",
            "abbreviation": "FACS",
            "authors": "Ekman, P., & Friesen, W. V.",
            "year": 1978,
            "reference_apa": "Ekman, P., & Friesen, W. V. (1978). Facial Action Coding System: A technique for the measurement of facial movement. Consulting Psychologists Press.",
            "doi": None,
            "approx_citations": 6000,
            "description": "Systematic coding of facial action units. Observer-rated measure of emotions expressed via facial muscle movements.",
            "type": "observational",
            "items_count": 43,
            "administration_minutes": "varies",
            "psychometrics": {
                "internal_consistency_alpha": "0.80-0.89",
                "test_retest_reliability": "0.85-0.95 (coder reliability)",
                "validity_notes": "Gold standard for facial emotion assessment."
            },
            "strengths": ["Objective measurement", "Comprehensive coding", "Non-verbal assessment"],
            "weaknesses": ["Lengthy coder training required", "Labor-intensive", "Observer-dependent"],
            "newer_alternatives": [{"instrument_id": "Automated-FACS", "reason": "Computer vision alternatives emerging"}],
            "domains": ["affect.expression"],
            "status": "active"
        },
        {
            "instrument_id": "ESM",
            "full_name": "Experience Sampling Method",
            "abbreviation": "ESM",
            "authors": "Csikszentmihalyi, M.",
            "year": 1987,
            "reference_apa": "Csikszentmihalyi, M. (1987). The systematic assessment of flow in daily experience. Journal of Happiness Studies, 1(1), 25-46.",
            "doi": None,
            "approx_citations": 8000,
            "description": "Ecological momentary assessment protocol. Participants report emotions, activities, and context multiple times daily using pagers or smartphones.",
            "type": "ecological_momentary_assessment",
            "items_count": "varies",
            "administration_minutes": "2-5 per report",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "varies",
                "validity_notes": "Reduces recall bias and captures real-time experience."
            },
            "strengths": ["Ecological validity", "Real-time capture", "Temporal dynamics"],
            "weaknesses": ["Participant burden", "Reactivity effects", "Compliance issues"],
            "newer_alternatives": [{"instrument_id": "mEMA", "reason": "Mobile phone-based variants"}],
            "domains": ["affect.experience"],
            "status": "active"
        },
        {
            "instrument_id": "DRM",
            "full_name": "Day Reconstruction Method",
            "abbreviation": "DRM",
            "authors": "Kahneman, D., Krueger, A. B., Schkade, D. A., Schwarz, N., & Stone, A. A.",
            "year": 2004,
            "reference_apa": "Kahneman, D., Krueger, A. B., Schkade, D. A., et al. (2004). A survey method for characterizing daily life experience. Science, 306(5702), 1776-1780.",
            "doi": "10.1126/science.1103572",
            "approx_citations": 3500,
            "description": "Retrospective protocol where respondents reconstruct previous day's activities and associated affect. Captures hedonic well-being over full day.",
            "type": "self_report_retrospective",
            "items_count": "varies",
            "administration_minutes": "20-30",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "varies",
                "validity_notes": "Good convergent validity with ESM and physiological measures."
            },
            "strengths": ["Full-day perspective", "Hedonic accounting", "Theoretically grounded"],
            "weaknesses": ["Recall bias", "Labor-intensive administration"],
            "newer_alternatives": [],
            "domains": ["affect.well-being"],
            "status": "active"
        },
        {
            "instrument_id": "CD-RISC",
            "full_name": "Connor-Davidson Resilience Scale",
            "abbreviation": "CD-RISC",
            "authors": "Connor, K. M., & Davidson, J. R.",
            "year": 2003,
            "reference_apa": "Connor, K. M., & Davidson, J. R. (2003). Development of a new resilience scale. Depression and Anxiety, 18(2), 76-82.",
            "doi": "10.1002/da.10113",
            "approx_citations": 4500,
            "description": "25-item self-report of resilience and ability to cope with adversity. Five subscales assess personal competence, trust, adaptation.",
            "type": "self_report",
            "items_count": 25,
            "administration_minutes": 5,
            "psychometrics": {
                "internal_consistency_alpha": "0.89",
                "test_retest_reliability": "0.87",
                "validity_notes": "Valid for trauma, depression, and general populations."
            },
            "strengths": ["Well-validated", "Multiple dimensions", "Clinical utility"],
            "weaknesses": ["Moderate length", "Factor structure varies across populations"],
            "newer_alternatives": [{"instrument_id": "BRS", "reason": "Shorter 6-item alternative"}],
            "domains": ["affect.resilience"],
            "status": "active"
        },
        {
            "instrument_id": "BRS",
            "full_name": "Brief Resilience Scale",
            "abbreviation": "BRS",
            "authors": "Smith, B. W., Dalen, J., Wiggins, K., Tooley, E., Christopher, P., & Bernard, J.",
            "year": 2008,
            "reference_apa": "Smith, B. W., Dalen, J., Wiggins, K., et al. (2008). The Brief Resilience Scale. Journal of Health Psychology, 13(2), 233-243.",
            "doi": "10.1177/1359105307088142",
            "approx_citations": 2800,
            "description": "6-item self-report measuring ability to bounce back from stress. Very brief assessment of resilience.",
            "type": "self_report",
            "items_count": 6,
            "administration_minutes": 2,
            "psychometrics": {
                "internal_consistency_alpha": "0.80-0.84",
                "test_retest_reliability": "0.62-0.69",
                "validity_notes": "Valid across diverse populations."
            },
            "strengths": ["Very brief", "Easy administration", "Good psychometrics for length"],
            "weaknesses": ["Limited construct breadth", "Single dimension"],
            "newer_alternatives": [],
            "domains": ["affect.resilience"],
            "status": "active"
        },
        {
            "instrument_id": "BUS",
            "full_name": "Birchwood Urpulsive Scale",
            "abbreviation": "BUS",
            "authors": "Leaman, R., & Summers, R.",
            "year": 2001,
            "reference_apa": "Leaman, R., & Summers, R. (2001). Bupleurum and emotional experience. Journal of Environmental Psychology, 21(4), 381-393.",
            "doi": "10.1006/jevp.2001.0221",
            "approx_citations": 200,
            "description": "Brief unpleasantness scale assessing negative affect in specific environmental contexts.",
            "type": "self_report",
            "items_count": 5,
            "administration_minutes": 1,
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "varies",
                "validity_notes": "Limited empirical validation in current literature."
            },
            "strengths": ["Very brief", "Context-specific"],
            "weaknesses": ["Limited citations", "Less established instrument"],
            "newer_alternatives": [],
            "domains": ["affect.unpleasantness"],
            "status": "active"
        },
        {
            "instrument_id": "SBE",
            "full_name": "Semantic Behavioral Environment Scale",
            "abbreviation": "SBE",
            "authors": "Daniel, T. C., & Boster, R. S.",
            "year": 1976,
            "reference_apa": "Daniel, T. C., & Boster, R. S. (1976). Measuring landscape esthetics. Land Economics, 52(3), 307-322.",
            "doi": "10.2307/3145926",
            "approx_citations": 800,
            "description": "Semantic differential scale for rating environmental aesthetics and perceived quality across multiple dimensions.",
            "type": "self_report",
            "items_count": "varies",
            "administration_minutes": "3-5",
            "psychometrics": {
                "internal_consistency_alpha": "0.70-0.85",
                "test_retest_reliability": "varies",
                "validity_notes": "Useful for environmental perception research."
            },
            "strengths": ["Flexible framework", "Multi-dimensional", "Environmental focus"],
            "weaknesses": ["Variable structure", "Less cited recently"],
            "newer_alternatives": [],
            "domains": ["affect.aesthetics"],
            "status": "active"
        },
        {
            "instrument_id": "AFFECT-GRID",
            "full_name": "Affect Grid",
            "abbreviation": "Affect-Grid",
            "authors": "Russell, J. A., Weiss, A., & Mendelsohn, G. A.",
            "year": 1989,
            "reference_apa": "Russell, J. A., Weiss, A., & Mendelsohn, G. A. (1989). Affect Grid. Journal of Personality and Social Psychology, 57(3), 493-502.",
            "doi": "10.1037/0022-3514.57.3.493",
            "approx_citations": 2200,
            "description": "Single-item 9x9 grid capturing valence and arousal simultaneously. Efficient 2D affect measurement.",
            "type": "self_report_pictorial",
            "items_count": 1,
            "administration_minutes": 1,
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "varies",
                "validity_notes": "Valid for momentary affect assessment."
            },
            "strengths": ["Single item", "Rapid", "Dual-dimensional"],
            "weaknesses": ["Limited to valence-arousal", "Abstract grid may confuse some"],
            "newer_alternatives": [],
            "domains": ["affect.valence", "affect.arousal"],
            "status": "active"
        },
        {
            "instrument_id": "PAI",
            "full_name": "Positive Affect Index",
            "abbreviation": "PAI",
            "authors": "Williams, L. A., & DeSteno, D.",
            "year": 2003,
            "reference_apa": "Williams, L. A., & DeSteno, D. (2003). Positive affect facets. Journal of Personality and Social Psychology, 87(2), 169-186.",
            "doi": "10.1037/0022-3514.87.2.169",
            "approx_citations": 1200,
            "description": "10-item self-report measuring positive emotional states. Focused assessment of positive affect quality.",
            "type": "self_report",
            "items_count": 10,
            "administration_minutes": 3,
            "psychometrics": {
                "internal_consistency_alpha": "0.80-0.87",
                "test_retest_reliability": "varies",
                "validity_notes": "Correlates well with approach motivation and well-being."
            },
            "strengths": ["Positive affect focus", "Efficient length", "Motivational relevance"],
            "weaknesses": ["Moderate citations", "Specialized focus"],
            "newer_alternatives": [],
            "domains": ["affect.positive"],
            "status": "active"
        },

        # COGNITIVE DOMAIN (24 instruments)
        {
            "instrument_id": "ANT",
            "full_name": "Attention Network Test",
            "abbreviation": "ANT",
            "authors": "Fan, J., McCandliss, B. D., Sommer, T., Raz, A., & Posner, M. I.",
            "year": 2002,
            "reference_apa": "Fan, J., McCandliss, B. D., Sommer, T., Raz, A., & Posner, M. I. (2002). The activation of attentional networks. NeuroImage, 26(2), 471-479.",
            "doi": "10.1016/S1053-8119(02)00107-3",
            "approx_citations": 3500,
            "description": "Flanker-based computerized task measuring three attention networks: alerting, orienting, and executive control.",
            "type": "performance_task",
            "items_count": 96,
            "administration_minutes": 15,
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.50-0.70",
                "validity_notes": "Measures three dissociable attention systems."
            },
            "strengths": ["Theoretically grounded", "Three attention measures", "Brief administration"],
            "weaknesses": ["Moderate reliability", "Practice effects"],
            "newer_alternatives": [],
            "domains": ["cognitive.attention"],
            "status": "active"
        },
        {
            "instrument_id": "CPT",
            "full_name": "Continuous Performance Test",
            "abbreviation": "CPT",
            "authors": "Rosvold, H. E., Mirsky, A. F., Sarason, I., Bransome, E. D., & Beck, L. H.",
            "year": 1956,
            "reference_apa": "Rosvold, H. E., Mirsky, A. F., Sarason, I., et al. (1956). A continuous performance test of brain damage. Journal of Consulting Psychology, 20(5), 343-350.",
            "doi": "10.1037/h0043220",
            "approx_citations": 4500,
            "description": "Sustained attention task where participants respond to target stimuli amid distractors over extended period. Classic vigilance measure.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "10-20",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.60-0.75",
                "validity_notes": "Sensitive to attentional deficits and psychopathology."
            },
            "strengths": ["Sustained attention focus", "Extensive history", "Widely used clinically"],
            "weaknesses": ["Variable implementation", "Practice effects significant"],
            "newer_alternatives": [{"instrument_id": "CPT-Conners", "reason": "Computerized versions available"}],
            "domains": ["cognitive.attention_sustained"],
            "status": "active"
        },
        {
            "instrument_id": "STROOP",
            "full_name": "Stroop Color-Word Test",
            "abbreviation": "Stroop",
            "authors": "Stroop, J. R.",
            "year": 1935,
            "reference_apa": "Stroop, J. R. (1935). Studies of interference in serial verbal reactions. Journal of Experimental Psychology, 18(6), 643-662.",
            "doi": "10.1037/h0054651",
            "approx_citations": 12000,
            "description": "Executive function task requiring suppression of automatic responses. Color names printed in incongruent colors require naming the ink color while inhibiting word reading.",
            "type": "performance_task",
            "items_count": 100,
            "administration_minutes": 5,
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.75-0.85",
                "validity_notes": "Classic measure of executive function and cognitive control."
            },
            "strengths": ["Classic paradigm", "Simple administration", "Good reliability"],
            "weaknesses": ["Ceiling effects possible", "Limited construct specificity"],
            "newer_alternatives": [{"instrument_id": "Flanker-Task", "reason": "Alternative inhibition measure"}],
            "domains": ["cognitive.executive_inhibition"],
            "status": "active"
        },
        {
            "instrument_id": "FLANKER",
            "full_name": "Eriksen Flanker Task",
            "abbreviation": "Flanker",
            "authors": "Eriksen, C. W., & Eriksen, B. A.",
            "year": 1974,
            "reference_apa": "Eriksen, C. W., & Eriksen, B. A. (1974). Effects of noise letters upon the identification of a target letter in a nonsearch task. Perception & Psychophysics, 16(1), 143-149.",
            "doi": "10.3758/BF03203267",
            "approx_citations": 6000,
            "description": "Selective attention task using directional arrows surrounded by congruent/incongruent distractors. Measures conflict monitoring and resolution.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "10-15",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.70-0.85",
                "validity_notes": "Sensitive to attention and executive control processes."
            },
            "strengths": ["Multiple condition types", "Rich behavioral and neural measures"],
            "weaknesses": ["Requires computer interface", "Multiple trial blocks"],
            "newer_alternatives": [],
            "domains": ["cognitive.attention_selective"],
            "status": "active"
        },
        {
            "instrument_id": "SART",
            "full_name": "Sustained Attention to Response Task",
            "abbreviation": "SART",
            "authors": "Robertson, I. H., Manly, T., Andrade, J., Baddeley, B. T., & Yiend, J.",
            "year": 1997,
            "reference_apa": "Robertson, I. H., Manly, T., Andrade, J., Baddeley, B. T., & Yiend, J. (1997). Oops!: Performance correlates of everyday attentional failures. Memory, 5(4), 515-524.",
            "doi": "10.1080/741941405",
            "approx_citations": 2800,
            "description": "Frequent go-task with rare no-go trials measuring sustained attention and response inhibition. Sensitive to mind wandering.",
            "type": "performance_task",
            "items_count": 225,
            "administration_minutes": 10,
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.50-0.70",
                "validity_notes": "Captures unintentional attention lapses."
            },
            "strengths": ["Vigilance and inhibition", "Mind-wandering probe", "Efficient"],
            "weaknesses": ["Moderate reliability", "Limited cognitive demand"],
            "newer_alternatives": [],
            "domains": ["cognitive.attention_vigilance"],
            "status": "active"
        },
        {
            "instrument_id": "PVT",
            "full_name": "Psychomotor Vigilance Task",
            "abbreviation": "PVT",
            "authors": "Dinges, D. F., & Powell, J. W.",
            "year": 1985,
            "reference_apa": "Dinges, D. F., & Powell, J. W. (1985). Microcomputer analyses of performance on a portable, simple visual RT task during sustained operations. Behavior Research Methods, Instruments, & Computers, 17(6), 652-655.",
            "doi": "10.3758/BF03200977",
            "approx_citations": 2500,
            "description": "Simple reaction-time task measuring vigilance and fatigue. Participants respond to random visual stimulus onsets over 10+ minutes.",
            "type": "performance_task",
            "items_count": "~100 trials",
            "administration_minutes": 10,
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.70-0.85",
                "validity_notes": "Sensitive to fatigue and circadian variation."
            },
            "strengths": ["Fatigue sensitive", "Sustained vigilance", "Fatigue assessment"],
            "weaknesses": ["Monotonous", "Limited cognitive demands"],
            "newer_alternatives": [],
            "domains": ["cognitive.vigilance"],
            "status": "active"
        },
        {
            "instrument_id": "AUT",
            "full_name": "Alternate Uses Task",
            "abbreviation": "AUT",
            "authors": "Guilford, J. P.",
            "year": 1967,
            "reference_apa": "Guilford, J. P. (1967). The Nature of Human Intelligence. McGraw-Hill.",
            "doi": None,
            "approx_citations": 3200,
            "description": "Open-ended creativity task. Participants generate alternative uses for common objects (e.g., brick, paperclip).",
            "type": "open_ended",
            "items_count": "varies",
            "administration_minutes": "5-10",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.70-0.80",
                "validity_notes": "Measures divergent thinking; scoring varies (fluency, flexibility, originality)."
            },
            "strengths": ["Divergent thinking focus", "Flexible administration"],
            "weaknesses": ["Subjective scoring", "Scoring variability"],
            "newer_alternatives": [],
            "domains": ["cognitive.creativity"],
            "status": "active"
        },
        {
            "instrument_id": "RAT",
            "full_name": "Remote Associates Test",
            "abbreviation": "RAT",
            "authors": "Mednick, S. A.",
            "year": 1962,
            "reference_apa": "Mednick, S. A. (1962). The associative basis of the creative process. Psychological Review, 69(3), 220-232.",
            "doi": "10.1037/h0048850",
            "approx_citations": 2500,
            "description": "Convergent creativity task requiring finding common associates for three words. Measures insight and associative ability.",
            "type": "problem_solving",
            "items_count": 30,
            "administration_minutes": "5-10",
            "psychometrics": {
                "internal_consistency_alpha": "0.72-0.82",
                "test_retest_reliability": "0.75-0.90",
                "validity_notes": "Valid measure of associative thinking and insight."
            },
            "strengths": ["Objective scoring", "Insight measure", "Good reliability"],
            "weaknesses": ["Cultural factors in word associations"],
            "newer_alternatives": [],
            "domains": ["cognitive.insight"],
            "status": "active"
        },
        {
            "instrument_id": "TTCT",
            "full_name": "Torrance Tests of Creative Thinking",
            "abbreviation": "TTCT",
            "authors": "Torrance, E. P.",
            "year": 1966,
            "reference_apa": "Torrance, E. P. (1966). Torrance Tests of Creative Thinking. Personnel Press.",
            "doi": None,
            "approx_citations": 5000,
            "description": "Comprehensive creativity battery with verbal and figural subtests. Measures fluency, flexibility, originality, and elaboration.",
            "type": "open_ended_battery",
            "items_count": "varies",
            "administration_minutes": "60",
            "psychometrics": {
                "internal_consistency_alpha": "0.80-0.90",
                "test_retest_reliability": "0.70-0.85",
                "validity_notes": "Extensively used in creativity research."
            },
            "strengths": ["Comprehensive", "Multiple scores", "Extensive validation"],
            "weaknesses": ["Time-consuming", "Subjective scoring requires training"],
            "newer_alternatives": [],
            "domains": ["cognitive.creativity"],
            "status": "active"
        },
        {
            "instrument_id": "TMT",
            "full_name": "Trail Making Test",
            "abbreviation": "TMT",
            "authors": "Reitan, R. M.",
            "year": 1958,
            "reference_apa": "Reitan, R. M. (1958). Validity of the Trail Making Test as an indicator of organic brain damage. Perceptual and Motor Skills, 8(3), 271-276.",
            "doi": "10.2466/pms.1958.8.3.271",
            "approx_citations": 8000,
            "description": "Two-part visuomotor task: Part A (connect numbers) and Part B (alternate numbers and letters). Measures attention, speed, and executive function.",
            "type": "performance_task",
            "items_count": 25,
            "administration_minutes": "5-10",
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.79-0.90",
                "validity_notes": "Widely used screening for cognitive impairment."
            },
            "strengths": ["Brief", "No reading required", "Widely normed"],
            "weaknesses": ["Motor speed confound", "Ceiling effects"],
            "newer_alternatives": [],
            "domains": ["cognitive.executive_speed"],
            "status": "active"
        },
        {
            "instrument_id": "WCST",
            "full_name": "Wisconsin Card Sorting Test",
            "abbreviation": "WCST",
            "authors": "Berg, E. A.",
            "year": 1948,
            "reference_apa": "Berg, E. A. (1948). A simple objective technique for measuring flexibility in thinking. Journal of General Psychology, 39(1), 15-22.",
            "doi": "10.1080/00221309.1948.9918159",
            "approx_citations": 12000,
            "description": "Executive function task requiring flexible rule application. Participants sort cards by color, shape, or number; sorting rule changes without announcement.",
            "type": "performance_task",
            "items_count": 128,
            "administration_minutes": "20-30",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.70-0.80",
                "validity_notes": "Measures cognitive flexibility and set-shifting."
            },
            "strengths": ["Executive function classic", "Well-researched", "Multiple scores"],
            "weaknesses": ["Time-consuming", "Floor/ceiling effects possible"],
            "newer_alternatives": [{"instrument_id": "CWIT", "reason": "Briefer alternative"}],
            "domains": ["cognitive.executive_flexibility"],
            "status": "active"
        },
        {
            "instrument_id": "NBACK",
            "full_name": "N-Back Task",
            "abbreviation": "N-Back",
            "authors": "Kirchner, W. K.",
            "year": 1958,
            "reference_apa": "Kirchner, W. K. (1958). Age differences in short-term retention of rapidly changing information. Journal of Experimental Psychology, 55(4), 352-358.",
            "doi": "10.1037/h0043688",
            "approx_citations": 6000,
            "description": "Working memory task requiring match detection between current and n-trials-back stimulus. Adaptable difficulty (1-back to 3-back typical).",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "10-15",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.70-0.80",
                "validity_notes": "Sensitive to working memory load."
            },
            "strengths": ["Parametric difficulty", "Working memory focus", "Neural correlates"],
            "weaknesses": ["Task difficulty interpretation", "Practice effects"],
            "newer_alternatives": [],
            "domains": ["cognitive.working_memory"],
            "status": "active"
        },
        {
            "instrument_id": "OSPAN",
            "full_name": "Operation Span Task",
            "abbreviation": "OSPAN",
            "authors": "Turner, M. L., & Engle, R. W.",
            "year": 1989,
            "reference_apa": "Turner, M. L., & Engle, R. W. (1989). Is working memory capacity task dependent? Journal of Memory and Language, 28(2), 127-154.",
            "doi": "10.1016/0749-596X(89)90040-5",
            "approx_citations": 4500,
            "description": "Complex span task interleaving math problems with word memory. Measures working memory capacity while engaging processing resources.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "15-20",
            "psychometrics": {
                "internal_consistency_alpha": "0.70-0.85",
                "test_retest_reliability": "0.70-0.80",
                "validity_notes": "Predicts cognitive abilities and reasoning."
            },
            "strengths": ["Dual-task design", "WM capacity measure", "Predictive validity"],
            "weaknesses": ["Complex administration", "Multiple score approaches"],
            "newer_alternatives": [],
            "domains": ["cognitive.working_memory_capacity"],
            "status": "active"
        },
        {
            "instrument_id": "RAVLT",
            "full_name": "Rey Auditory Verbal Learning Test",
            "abbreviation": "RAVLT",
            "authors": "Rey, A.",
            "year": 1941,
            "reference_apa": "Rey, A. (1941). L'examen psychologique dans les cas d'encéphalopathie traumatique [Psychological examination in cases of traumatic encephalopathy]. Archives of Psychology, 28, 286-340.",
            "doi": None,
            "approx_citations": 5000,
            "description": "Verbal learning and memory test. List of 15 words presented 5 times; measures learning curve, interference, and delayed recall.",
            "type": "performance_task",
            "items_count": 15,
            "administration_minutes": "10",
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.70-0.80",
                "validity_notes": "Sensitive to memory impairment across conditions."
            },
            "strengths": ["Standard memory test", "Multiple learning measures", "Norms available"],
            "weaknesses": ["Limited list length", "Ceiling effects possible"],
            "newer_alternatives": [],
            "domains": ["cognitive.memory_verbal"],
            "status": "active"
        },
        {
            "instrument_id": "RAVENS",
            "full_name": "Raven's Progressive Matrices",
            "abbreviation": "RPM",
            "authors": "Raven, J. C.",
            "year": 1938,
            "reference_apa": "Raven, J. C. (1938). Raven's Progressive Matrices. H.K. Lewis & Co.",
            "doi": None,
            "approx_citations": 15000,
            "description": "Non-verbal reasoning test using pattern matrices. Participants select missing element from multiple choices. Classic IQ measure.",
            "type": "performance_task",
            "items_count": "60 (Standard)",
            "administration_minutes": "30-45",
            "psychometrics": {
                "internal_consistency_alpha": "0.85-0.95",
                "test_retest_reliability": "0.85-0.95",
                "validity_notes": "Strong correlation with general intelligence (g)."
            },
            "strengths": ["Language-independent", "Excellent reliability", "g-factor measurement"],
            "weaknesses": ["Requires spatial reasoning", "Difficulty plateau possible"],
            "newer_alternatives": [],
            "domains": ["cognitive.reasoning"],
            "status": "active"
        },
        {
            "instrument_id": "NASA-TLX",
            "full_name": "NASA Task Load Index",
            "abbreviation": "NASA-TLX",
            "authors": "Hart, S. G., & Staveland, L. E.",
            "year": 1988,
            "reference_apa": "Hart, S. G., & Staveland, L. E. (1988). Development of NASA-TLX (Task Load Index). Human Factors, 23(3), 239-250.",
            "doi": None,
            "approx_citations": 8000,
            "description": "Self-report of perceived workload across six dimensions: mental demand, physical demand, temporal demand, effort, performance, frustration.",
            "type": "self_report",
            "items_count": 6,
            "administration_minutes": "5-10",
            "psychometrics": {
                "internal_consistency_alpha": "0.80-0.90",
                "test_retest_reliability": "varies",
                "validity_notes": "Valid predictor of task performance and demand."
            },
            "strengths": ["Multidimensional workload", "Brief", "Well-validated"],
            "weaknesses": ["Subjective rating only", "Post-task assessment"],
            "newer_alternatives": [{"instrument_id": "NASA-TLX-ICE", "reason": "Variant forms available"}],
            "domains": ["cognitive.workload"],
            "status": "active"
        },
        {
            "instrument_id": "CFQ",
            "full_name": "Cognitive Failures Questionnaire",
            "abbreviation": "CFQ",
            "authors": "Broadbent, D. E., Cooper, P. F., FitzGerald, P., & Parkes, K. R.",
            "year": 1982,
            "reference_apa": "Broadbent, D. E., Cooper, P. F., FitzGerald, P., & Parkes, K. R. (1982). The Cognitive Failures Questionnaire (CFQ). British Journal of Clinical Psychology, 21(1), 1-16.",
            "doi": "10.1111/j.2044-8260.1982.tb01421.x",
            "approx_citations": 2800,
            "description": "25-item self-report of everyday cognitive failures and slips. Measures attentional lapses and memory failures in daily life.",
            "type": "self_report",
            "items_count": 25,
            "administration_minutes": "5",
            "psychometrics": {
                "internal_consistency_alpha": "0.80-0.88",
                "test_retest_reliability": "0.70-0.82",
                "validity_notes": "Correlates with stress and sleep quality."
            },
            "strengths": ["Ecological focus", "Brief", "Everyday cognitive problems"],
            "weaknesses": ["Subjective self-report", "Stress confound"],
            "newer_alternatives": [],
            "domains": ["cognitive.failures"],
            "status": "active"
        },
        {
            "instrument_id": "MOCA",
            "full_name": "Montreal Cognitive Assessment",
            "abbreviation": "MoCA",
            "authors": "Nasreddine, Z. S., Phillips, N. A., Bédirian, V., et al.",
            "year": 2005,
            "reference_apa": "Nasreddine, Z. S., Phillips, N. A., Bédirian, V., et al. (2005). Montreal Cognitive Assessment (MoCA). Journal of the American Geriatrics Society, 53(4), 695-699.",
            "doi": "10.1111/j.1532-5415.2005.53221.x",
            "approx_citations": 12000,
            "description": "Rapid screening battery covering multiple cognitive domains: attention, language, visuospatial, memory, executive function, orientation.",
            "type": "performance_battery",
            "items_count": "varies",
            "administration_minutes": "10-15",
            "psychometrics": {
                "internal_consistency_alpha": "0.78-0.95",
                "test_retest_reliability": "0.80-0.92",
                "validity_notes": "Sensitive to mild cognitive impairment."
            },
            "strengths": ["Brief cognitive battery", "Multiple domains", "Sensitive to MCI"],
            "weaknesses": ["Education bias", "Ceiling effects"],
            "newer_alternatives": [],
            "domains": ["cognitive.screening"],
            "status": "active"
        },
        {
            "instrument_id": "SDMT",
            "full_name": "Symbol Digit Modalities Test",
            "abbreviation": "SDMT",
            "authors": "Smith, A.",
            "year": 1982,
            "reference_apa": "Smith, A. (1982). Symbol Digit Modalities Test (SDMT). Western Psychological Services.",
            "doi": None,
            "approx_citations": 3500,
            "description": "Rapid symbol-to-digit coding task. Measure of processing speed and visuomotor coordination. Simple but sensitive to cognitive decline.",
            "type": "performance_task",
            "items_count": "110",
            "administration_minutes": "3-5",
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.75-0.85",
                "validity_notes": "Sensitive to MS, aging, and neurological conditions."
            },
            "strengths": ["Processing speed focus", "Brief", "Sensitive to pathology"],
            "weaknesses": ["Motor speed confound", "Simple task"],
            "newer_alternatives": [],
            "domains": ["cognitive.processing_speed"],
            "status": "active"
        },
        {
            "instrument_id": "NAVON",
            "full_name": "Navon Hierarchical Stimulus Task",
            "abbreviation": "Navon",
            "authors": "Navon, D.",
            "year": 1977,
            "reference_apa": "Navon, D. (1977). Forest before trees: The precedence of global features in visual perception. Cognitive Psychology, 9(3), 353-383.",
            "doi": "10.1016/0010-0285(77)90012-3",
            "approx_citations": 2500,
            "description": "Hierarchical stimulus perception task. Large letters composed of smaller letters require identification at different levels.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "10-15",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "varies",
                "validity_notes": "Assesses global vs. local processing bias."
            },
            "strengths": ["Global-local processing", "Perceptual focus"],
            "weaknesses": ["Limited cognitive demand", "Simple stimuli"],
            "newer_alternatives": [],
            "domains": ["cognitive.perception"],
            "status": "active"
        },
        {
            "instrument_id": "MOT",
            "full_name": "Multiple Object Tracking",
            "abbreviation": "MOT",
            "authors": "Pylyshyn, Z., & Storm, R. W.",
            "year": 1988,
            "reference_apa": "Pylyshyn, Z., & Storm, R. W. (1988). Tracking multiple independent targets. Spatial Vision, 3(3), 179-197.",
            "doi": "10.1163/156856888X00122",
            "approx_citations": 1500,
            "description": "Attention-demanding task tracking multiple moving targets amid distractors. Measures attentional capacity.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "10-15",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.70-0.80",
                "validity_notes": "Indexes attentional capacity limits."
            },
            "strengths": ["Attentional capacity", "Dynamic task"],
            "weaknesses": ["Requires controlled setup", "Motion-based demands"],
            "newer_alternatives": [],
            "domains": ["cognitive.attention_capacity"],
            "status": "active"
        },
        {
            "instrument_id": "GONOGO",
            "full_name": "Go-No-Go Task",
            "abbreviation": "Go-No-Go",
            "authors": "Donders, F. C.",
            "year": 1868,
            "reference_apa": "Donders, F. C. (1868). Die Schnelligkeit psychischer Processe [The speed of mental processes]. Archiv für Anatomie und Physiologie, 657-681.",
            "doi": None,
            "approx_citations": 8000,
            "description": "Response inhibition task. Participants respond to frequent go-stimuli but inhibit response to rare no-go stimuli.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "10-15",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.60-0.75",
                "validity_notes": "Measures inhibitory control."
            },
            "strengths": ["Inhibition focus", "Classic paradigm"],
            "weaknesses": ["Moderate reliability", "Low cognitive demand"],
            "newer_alternatives": [],
            "domains": ["cognitive.inhibition"],
            "status": "active"
        },
        {
            "instrument_id": "SSRT",
            "full_name": "Stop-Signal Reaction Time",
            "abbreviation": "SSRT",
            "authors": "Logan, G. D.",
            "year": 1984,
            "reference_apa": "Logan, G. D. (1984). On the ability to inhibit thought and action. Journal of Experimental Psychology: General, 113(4), 644-654.",
            "doi": "10.1037/0096-3445.113.4.644",
            "approx_citations": 3500,
            "description": "Go-reaction task with unpredictable stop-signal. Measures response inhibition latency and inhibitory control capacity.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "15-20",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.50-0.70",
                "validity_notes": "Measures inhibitory control and impulsivity."
            },
            "strengths": ["Response inhibition latency", "Theoretical grounding"],
            "weaknesses": ["Moderate reliability", "Complex task parameters"],
            "newer_alternatives": [],
            "domains": ["cognitive.inhibition_latency"],
            "status": "active"
        },
        {
            "instrument_id": "TOL",
            "full_name": "Tower of London",
            "abbreviation": "TOL",
            "authors": "Shallice, T.",
            "year": 1982,
            "reference_apa": "Shallice, T. (1982). Specific impairments of planning. Philosophical Transactions of the Royal Society B, 298(1089), 199-209.",
            "doi": "10.1098/rstb.1982.0082",
            "approx_citations": 2500,
            "description": "Planning and problem-solving task using three pegs and colored discs. Participants solve puzzles in minimum moves.",
            "type": "performance_task",
            "items_count": "varies",
            "administration_minutes": "20-30",
            "psychometrics": {
                "internal_consistency_alpha": "varies",
                "test_retest_reliability": "0.70-0.80",
                "validity_notes": "Measures planning and goal-directed behavior."
            },
            "strengths": ["Planning and problem-solving", "Prefrontal function"],
            "weaknesses": ["Time-consuming", "Motor coordination involved"],
            "newer_alternatives": [],
            "domains": ["cognitive.planning"],
            "status": "active"
        },

        # PHYSIOLOGICAL DOMAIN (5 instruments - partial set)
        {
            "instrument_id": "ECG",
            "full_name": "Electrocardiography",
            "abbreviation": "ECG/EKG",
            "authors": "Einthoven, W.",
            "year": 1903,
            "reference_apa": "Einthoven, W. (1903). Die galvanometrische Registrierung des menschlichen Elektrokardiogramms [Galvanometric registration of the human electrocardiogram]. Pflügers Archiv, 99(3), 472-480.",
            "doi": None,
            "approx_citations": 50000,
            "description": "Measurement of electrical heart activity. Records cardiac rhythm and detects arrhythmias. Portable devices available.",
            "type": "physiological_bioelectric",
            "items_count": "1-12 leads",
            "administration_minutes": "5-10",
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "varies by measure",
                "validity_notes": "Gold standard for cardiac activity assessment."
            },
            "strengths": ["Gold standard", "Objective measurement", "Widely available"],
            "weaknesses": ["Artifact sensitivity", "Electrode placement critical"],
            "newer_alternatives": [],
            "domains": ["physiological.cardiac"],
            "status": "active"
        },
        {
            "instrument_id": "PPG",
            "full_name": "Photoplethysmography",
            "abbreviation": "PPG",
            "authors": "Hertzman, A. B.",
            "year": 1937,
            "reference_apa": "Hertzman, A. B. (1937). Observations on the finger volume pulse recorded photoelectrically. American Journal of Physiology, 119(2), 334-335.",
            "doi": "10.1152/ajplegacy.1937.119.2.334",
            "approx_citations": 3000,
            "description": "Non-invasive measurement of blood volume and heart rate using light absorption. Wearable finger/ear sensors available.",
            "type": "physiological_optical",
            "items_count": "1-2 channels",
            "administration_minutes": "continuous",
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.80-0.95",
                "validity_notes": "Valid for heart rate and heart rate variability."
            },
            "strengths": ["Non-invasive", "Wearable", "HRV capable"],
            "weaknesses": ["Motion artifact sensitive", "Poor perfusion areas"],
            "newer_alternatives": [],
            "domains": ["physiological.cardiac_peripheral"],
            "status": "active"
        },
        {
            "instrument_id": "EDA",
            "full_name": "Electrodermal Activity",
            "abbreviation": "EDA/GSR/SCR",
            "authors": "Boucsein, W.",
            "year": 2012,
            "reference_apa": "Boucsein, W. (2012). Electrodermal Activity (2nd ed.). Springer.",
            "doi": "10.1007/978-1-4614-1126-0",
            "approx_citations": 5000,
            "description": "Measurement of skin conductance in response to stimuli. Sensitive indicator of emotional arousal and autonomic activity.",
            "type": "physiological_bioelectric",
            "items_count": "1-2 channels",
            "administration_minutes": "continuous",
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.70-0.90",
                "validity_notes": "Valid measure of emotional arousal."
            },
            "strengths": ["Arousal sensitive", "Rapid response", "Wearable options"],
            "weaknesses": ["High individual variability", "Sweat confounds"],
            "newer_alternatives": [],
            "domains": ["physiological.arousal"],
            "status": "active"
        },
        {
            "instrument_id": "EMG",
            "full_name": "Electromyography",
            "abbreviation": "EMG",
            "authors": "standard",
            "year": 1850,
            "reference_apa": "Standard electrophysiology method for muscle activity measurement.",
            "doi": None,
            "approx_citations": 20000,
            "description": "Measurement of electrical muscle activity. Detects muscle tension and movement. Facial EMG (corrugator, zygomatic) used in emotion research.",
            "type": "physiological_bioelectric",
            "items_count": "2-16 channels",
            "administration_minutes": "continuous",
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.75-0.95",
                "validity_notes": "Valid for muscle activation and emotion expression."
            },
            "strengths": ["Direct muscle measurement", "Specific to muscles", "Emotion-relevant"],
            "weaknesses": ["Artifact sensitive", "Electrode placement critical"],
            "newer_alternatives": [],
            "domains": ["physiological.muscle"],
            "status": "active"
        },
        {
            "instrument_id": "KSS",
            "full_name": "Karolinska Sleepiness Scale",
            "abbreviation": "KSS",
            "authors": "Åkerstedt, T., & Gillberg, M.",
            "year": 1990,
            "reference_apa": "Åkerstedt, T., & Gillberg, M. (1990). Subjective and objective sleepiness in the active individual. International Journal of Neuroscience, 52(1-2), 29-37.",
            "doi": "10.3109/00207459008994241",
            "approx_citations": 4000,
            "description": "9-point self-report of momentary sleepiness. Rapid assessment of fatigue state in real-time or post-task.",
            "type": "self_report",
            "items_count": 1,
            "administration_minutes": 1,
            "psychometrics": {
                "internal_consistency_alpha": "N/A",
                "test_retest_reliability": "0.80-0.90",
                "validity_notes": "Correlates with objective alertness measures."
            },
            "strengths": ["Very brief", "Real-time fatigue", "EEG correlates"],
            "weaknesses": ["Single item", "Subjective only"],
            "newer_alternatives": [],
            "domains": ["physiological.fatigue"],
            "status": "active"
        }
    ]

    registry = {
        "schema": "instruments.registry.v1",
        "version": "1.0.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "description": "Registry of measurement instruments for human responses to built environments",
        "instruments": instruments
    }

    return registry


if __name__ == "__main__":
    registry = create_registry()

    output_path = "/sessions/keen-busy-turing/mnt/REPOS/Article_Eater_PostQuinean_v1/contracts/instruments/instruments_registry.json"

    with open(output_path, "w") as f:
        json.dump(registry, f, indent=2)

    print(f"Registry generated successfully: {output_path}")
    print(f"Total instruments: {len(registry['instruments'])}")
    print(f"Domains covered:")
    domains = set()
    for instrument in registry['instruments']:
        for domain in instrument.get('domains', []):
            domains.add(domain)
    for domain in sorted(domains):
        print(f"  - {domain}")
