# GOVERNANCE CONFIG — GENERATED BY GOVERNANCE KIT V{{GOVERNANCE_KIT_VERSION}}
{
  "project_name": "{{PROJECT_NAME}}",
  "project_code": "{{PROJECT_CODE}}",
  "project_owner": "{{PROJECT_OWNER}}",
  "primary_ai_system": "{{PRIMARY_AI_SYSTEM}}",
  "primary_domain": "{{PRIMARY_DOMAIN}}",
  "governance_kit_version": "{{GOVERNANCE_KIT_VERSION}}",
  "install_date": "{{INSTALL_DATE}}",
  "paths": {
    "system_vision": ".governance/SYSTEM_VISION.md",
    "conversation_ledger": ".governance/CONVERSATION_LEDGER.yml",
    "project_constitution": ".governance/PROJECT_CONSTITUTION.md",
    "release_keep": ".governance/release.keep.yml",
    "deprecations": ".governance/deprecations.yml"
  },
  "rules": {
    "require_ledger_entry_for_major_change": true,
    "require_system_vision_present": true,
    "require_project_constitution_present": true,
    "warn_if_governance_kit_outdated": true
  },
  "drift_shield": {
    "enabled": {{DRIFT_SHIELD_ENABLED}},
    "require_release_keep_for_tagged_versions": true,
    "require_deprecations_tracking": true
  }
}