# System Vision — {{PROJECT_NAME}}

Generated by governance-kit-v{{GOVERNANCE_KIT_VERSION}} on {{INSTALL_DATE}}.

- Project code: {{PROJECT_CODE}}
- Primary domain: {{PRIMARY_DOMAIN}}
- Primary AI system: {{PRIMARY_AI_SYSTEM}}
- Project owner: {{PROJECT_OWNER}}

Briefly describe what this system is for and why it exists.