"""Core infrastructure for Article Eater."""

from src.core.logging import (
    bind_context,
    clear_context,
    configure_logging,
    get_logger,
)
from src.core.errors import (
    ArticleEaterError,
    BeliefNotFoundError,
    BridgeNotFoundError,
    CircularDependencyError,
    CoherenceError,
    ConfigurationError,
    ConstraintViolationError,
    DatabaseError,
    EntityNotFoundError,
    EpistemicError,
    ExtractionError,
    IntegrityError,
    InvalidConfigError,
    InvalidParameterError,
    LLMError,
    MigrationError,
    MissingConfigError,
    PaperNotFoundError,
    ParsingError,
    ProcessingError,
    SchemaValidationError,
    TemplateNotFoundError,
    TheoryNotFoundError,
    ValidationError,
)

__all__ = [
    # Logging
    "bind_context",
    "clear_context",
    "configure_logging",
    "get_logger",
    # Errors
    "ArticleEaterError",
    "BeliefNotFoundError",
    "BridgeNotFoundError",
    "CircularDependencyError",
    "CoherenceError",
    "ConfigurationError",
    "ConstraintViolationError",
    "DatabaseError",
    "EntityNotFoundError",
    "EpistemicError",
    "ExtractionError",
    "IntegrityError",
    "InvalidConfigError",
    "InvalidParameterError",
    "LLMError",
    "MigrationError",
    "MissingConfigError",
    "PaperNotFoundError",
    "ParsingError",
    "ProcessingError",
    "SchemaValidationError",
    "TemplateNotFoundError",
    "TheoryNotFoundError",
    "ValidationError",
]
