"""
Article Eater - Theory System Data Models
Sprint TH-1: Theory Data Model & Registry

Provides data classes and enums for representing theoretical frameworks,
their predictions, and evidence relationships.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import List, Dict, Any, Optional
from datetime import datetime
import json


# ============================================================
# ENUMS
# ============================================================

class TheoryLevel(Enum):
    """Hierarchical level of theoretical abstraction."""
    META_PRINCIPLE = "meta_principle"  # Most abstract (e.g., "moderate stimulation is optimal")
    THEORY = "theory"  # Unified explanatory framework (e.g., Predictive Processing)
    PRINCIPLE = "principle"  # Domain-specific regularity (e.g., "nature exposure reduces stress")
    MECHANISM = "mechanism"  # Pathway specification (e.g., "daylight → circadian → mood")


class Necessity(Enum):
    """Whether a claim is essential to the theory."""
    CORE = "core"  # Theory could not survive without this claim
    AUXILIARY = "auxiliary"  # Elaborates but not essential


class Testability(Enum):
    """How directly testable a claim is."""
    DIRECTLY_TESTABLE = "directly_testable"
    INDIRECTLY_TESTABLE = "indirectly_testable"
    FRAMEWORK = "framework"  # Provides structure but not directly testable


class PredictionType(Enum):
    """Source of a prediction."""
    EXPLICIT = "explicit"  # Stated by theory originators
    DERIVED = "derived"  # Logically implied by core claims
    NEWLY_DERIVED = "newly_derived"  # Generated by system inference


class Direction(Enum):
    """Predicted direction of effect."""
    POSITIVE = "positive"
    NEGATIVE = "negative"
    NULL = "null"
    INVERTED_U = "inverted_u"
    COMPLEX = "complex"


class Magnitude(Enum):
    """Predicted magnitude of effect."""
    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"
    UNSPECIFIED = "unspecified"


class RelationType(Enum):
    """Type of relationship predicted."""
    DETERMINISTIC = "deterministic"
    PROBABILISTIC = "probabilistic"
    TENDENCY = "tendency"


class Generality(Enum):
    """Scope of prediction applicability."""
    UNIVERSAL = "universal"
    DOMAIN_SPECIFIC = "domain_specific"
    POPULATION_SPECIFIC = "population_specific"
    CONTEXT_SPECIFIC = "context_specific"


class TestingStatus(Enum):
    """How well-tested a prediction is."""
    UNTESTED = "untested"
    PARTIALLY_TESTED = "partially_tested"
    WELL_TESTED = "well_tested"
    DISCONFIRMED = "disconfirmed"


class SupportLevel(Enum):
    """Overall empirical support for a prediction."""
    STRONGLY_SUPPORTED = "strongly_supported"
    SUPPORTED = "supported"
    MIXED = "mixed"
    UNSUPPORTED = "unsupported"
    DISCONFIRMED = "disconfirmed"
    UNTESTED = "untested"


class TestType(Enum):
    """How a study relates to testing a prediction."""
    DIRECT = "direct"  # Designed to test this prediction
    INDIRECT = "indirect"  # Bears on prediction but not designed for it
    INCIDENTAL = "incidental"  # Implications not recognized by authors


class TestResult(Enum):
    """Outcome of an empirical test."""
    SUPPORTS = "supports"
    PARTIAL = "partial"
    NULL = "null"
    CONTRADICTS = "contradicts"


class TestStrength(Enum):
    """Methodological strength of a test."""
    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"


class ReplicationStatus(Enum):
    """Overall replication record of a theory."""
    STRONG = "strong"
    MODERATE = "moderate"
    MIXED = "mixed"
    WEAK = "weak"
    CONTESTED = "contested"


class ContributionType(Enum):
    """How a paper contributes to a theory."""
    ORIGINATION = "origination"
    REFINEMENT = "refinement"
    EXTENSION = "extension"
    CRITIQUE = "critique"
    INTEGRATION = "integration"
    REVIEW = "review"


class UncertaintyType(Enum):
    """Source of uncertainty in a prediction."""
    ALEATORY = "aleatory"  # Inherent randomness
    EPISTEMIC = "epistemic"  # Lack of knowledge
    BOTH = "both"


# ============================================================
# DATA CLASSES
# ============================================================

@dataclass
class Originator:
    """Author/paper that originated or developed a theory."""
    name: str
    year: Optional[int] = None
    doi: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TheoryClaim:
    """A core claim or proposition of a theory."""
    claim_id: str
    theory_id: str
    statement: str
    formalization: Optional[str] = None
    necessity: Necessity = Necessity.CORE
    testability: Testability = Testability.DIRECTLY_TESTABLE
    created_at: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d['necessity'] = self.necessity.value
        d['testability'] = self.testability.value
        return d


@dataclass
class TheoryAssumption:
    """An assumption that a theory relies upon."""
    assumption_id: str
    theory_id: str
    statement: str
    dependent_claims: List[str] = field(default_factory=list)  # claim_ids
    violation_consequence: Optional[str] = None
    created_at: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TheoryBoundary:
    """A boundary condition where theory may not apply."""
    boundary_id: str
    theory_id: str
    condition_description: str
    evidence_for_boundary: List[str] = field(default_factory=list)  # citations
    mechanism_of_failure: Optional[str] = None
    confidence_penalty: float = 0.0
    created_at: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class DerivationStep:
    """A single step in a derivation chain."""
    claim_id: str
    inference_type: str  # e.g., "deductive", "inductive", "analogical"
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class QuantitativePrediction:
    """Quantitative aspects of a prediction."""
    point_estimate: Optional[float] = None
    ci_lower: Optional[float] = None
    ci_upper: Optional[float] = None
    functional_form: Optional[str] = None  # For complex relationships
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class Prediction:
    """A prediction derived from or explicit in a theory."""
    prediction_id: str
    source_theory_id: str
    statement: str
    prediction_type: PredictionType
    
    # Antecedent conditions
    antecedent_env_conditions: List[Dict[str, Any]] = field(default_factory=list)
    antecedent_population: List[Dict[str, Any]] = field(default_factory=list)
    antecedent_temporal: Optional[Dict[str, Any]] = None
    antecedent_state: List[Dict[str, Any]] = field(default_factory=list)
    
    # Consequent
    consequent_outcome: str = ""
    consequent_direction: Direction = Direction.POSITIVE
    consequent_magnitude: Magnitude = Magnitude.UNSPECIFIED
    consequent_mechanism: Optional[str] = None
    relation_type: RelationType = RelationType.PROBABILISTIC
    
    # Derivation
    derivation_chain: List[DerivationStep] = field(default_factory=list)
    auxiliary_assumptions: List[str] = field(default_factory=list)
    
    # Quantitative
    quantitative: Optional[QuantitativePrediction] = None
    
    # Scope
    generality: Generality = Generality.DOMAIN_SPECIFIC
    applicable_populations: List[str] = field(default_factory=list)
    applicable_contexts: List[str] = field(default_factory=list)
    known_exceptions: List[str] = field(default_factory=list)
    
    # Testing status
    testing_status: TestingStatus = TestingStatus.UNTESTED
    overall_support: SupportLevel = SupportLevel.UNTESTED
    test_summary: Optional[str] = None
    
    # Confidence
    prior_confidence: float = 0.5
    current_confidence: float = 0.5
    theory_contribution: float = 0.0
    derivation_contribution: float = 0.0
    empirical_contribution: float = 0.0
    uncertainty_type: UncertaintyType = UncertaintyType.EPISTEMIC
    
    # Network mapping
    maps_to_edge_id: Optional[str] = None
    maps_to_nodes: List[str] = field(default_factory=list)
    contributes_prior: bool = True
    prior_weight: float = 1.0
    
    # Metadata
    extraction_source: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        d = {
            'prediction_id': self.prediction_id,
            'source_theory_id': self.source_theory_id,
            'statement': self.statement,
            'prediction_type': self.prediction_type.value,
            'antecedent_env_conditions': self.antecedent_env_conditions,
            'antecedent_population': self.antecedent_population,
            'antecedent_temporal': self.antecedent_temporal,
            'antecedent_state': self.antecedent_state,
            'consequent_outcome': self.consequent_outcome,
            'consequent_direction': self.consequent_direction.value,
            'consequent_magnitude': self.consequent_magnitude.value,
            'consequent_mechanism': self.consequent_mechanism,
            'relation_type': self.relation_type.value,
            'derivation_chain': [s.to_dict() for s in self.derivation_chain],
            'auxiliary_assumptions': self.auxiliary_assumptions,
            'quantitative': self.quantitative.to_dict() if self.quantitative else None,
            'generality': self.generality.value,
            'applicable_populations': self.applicable_populations,
            'applicable_contexts': self.applicable_contexts,
            'known_exceptions': self.known_exceptions,
            'testing_status': self.testing_status.value,
            'overall_support': self.overall_support.value,
            'test_summary': self.test_summary,
            'prior_confidence': self.prior_confidence,
            'current_confidence': self.current_confidence,
            'theory_contribution': self.theory_contribution,
            'derivation_contribution': self.derivation_contribution,
            'empirical_contribution': self.empirical_contribution,
            'uncertainty_type': self.uncertainty_type.value,
            'maps_to_edge_id': self.maps_to_edge_id,
            'maps_to_nodes': self.maps_to_nodes,
            'contributes_prior': self.contributes_prior,
            'prior_weight': self.prior_weight,
            'extraction_source': self.extraction_source,
            'created_at': self.created_at,
            'updated_at': self.updated_at,
        }
        return d


@dataclass
class PredictionEvidence:
    """Evidence linking a study to a prediction test."""
    id: Optional[int] = None
    prediction_id: str = ""
    paper_id: str = ""
    finding_id: Optional[int] = None
    
    test_type: TestType = TestType.INDIRECT
    result: TestResult = TestResult.NULL
    test_strength: TestStrength = TestStrength.MODERATE
    
    conditions_met: bool = True
    notes: Optional[str] = None
    confidence_delta: float = 0.0
    
    created_at: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'id': self.id,
            'prediction_id': self.prediction_id,
            'paper_id': self.paper_id,
            'finding_id': self.finding_id,
            'test_type': self.test_type.value,
            'result': self.result.value,
            'test_strength': self.test_strength.value,
            'conditions_met': self.conditions_met,
            'notes': self.notes,
            'confidence_delta': self.confidence_delta,
            'created_at': self.created_at,
        }


@dataclass
class Theory:
    """A complete theoretical framework."""
    theory_id: str
    name: str
    aliases: List[str] = field(default_factory=list)
    
    # Origins
    originators: List[Originator] = field(default_factory=list)
    year_introduced: Optional[int] = None
    
    # Structure
    domain: List[str] = field(default_factory=list)  # Domain IDs
    scope_description: Optional[str] = None
    level: TheoryLevel = TheoryLevel.THEORY
    
    # Components (populated separately)
    core_claims: List[TheoryClaim] = field(default_factory=list)
    assumptions: List[TheoryAssumption] = field(default_factory=list)
    boundary_conditions: List[TheoryBoundary] = field(default_factory=list)
    
    # Predictions (populated separately)
    explicit_predictions: List[Prediction] = field(default_factory=list)
    derived_predictions: List[Prediction] = field(default_factory=list)
    
    # Confidence
    overall_confidence: float = 0.5
    confidence_rationale: Optional[str] = None
    quantitative_precision: str = "low"  # high, medium, low, none
    
    # Relations
    parent_theories: List[str] = field(default_factory=list)  # theory_ids
    child_theories: List[str] = field(default_factory=list)
    compatible_theories: List[str] = field(default_factory=list)
    competing_theories: List[str] = field(default_factory=list)
    
    # Evidence
    replication_status: ReplicationStatus = ReplicationStatus.MODERATE
    
    # Metadata
    extraction_source: Optional[str] = None
    extracted_by: Optional[str] = None
    version: int = 1
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    
    @property
    def all_predictions(self) -> List[Prediction]:
        """Return all predictions (explicit and derived)."""
        return self.explicit_predictions + self.derived_predictions
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'theory_id': self.theory_id,
            'name': self.name,
            'aliases': self.aliases,
            'originators': [o.to_dict() for o in self.originators],
            'year_introduced': self.year_introduced,
            'domain': self.domain,
            'scope_description': self.scope_description,
            'level': self.level.value,
            'core_claims': [c.to_dict() for c in self.core_claims],
            'assumptions': [a.to_dict() for a in self.assumptions],
            'boundary_conditions': [b.to_dict() for b in self.boundary_conditions],
            'explicit_predictions': [p.to_dict() for p in self.explicit_predictions],
            'derived_predictions': [p.to_dict() for p in self.derived_predictions],
            'overall_confidence': self.overall_confidence,
            'confidence_rationale': self.confidence_rationale,
            'quantitative_precision': self.quantitative_precision,
            'parent_theories': self.parent_theories,
            'child_theories': self.child_theories,
            'compatible_theories': self.compatible_theories,
            'competing_theories': self.competing_theories,
            'replication_status': self.replication_status.value,
            'extraction_source': self.extraction_source,
            'extracted_by': self.extracted_by,
            'version': self.version,
            'created_at': self.created_at,
            'updated_at': self.updated_at,
        }
    
    def to_json(self) -> str:
        """Serialize to JSON."""
        return json.dumps(self.to_dict(), indent=2)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Theory':
        """Deserialize from dictionary."""
        # Convert nested structures
        originators = [Originator(**o) for o in data.get('originators', [])]
        
        core_claims = []
        for c in data.get('core_claims', []):
            c['necessity'] = Necessity(c['necessity']) if isinstance(c['necessity'], str) else c['necessity']
            c['testability'] = Testability(c['testability']) if isinstance(c['testability'], str) else c['testability']
            core_claims.append(TheoryClaim(**c))
        
        assumptions = [TheoryAssumption(**a) for a in data.get('assumptions', [])]
        boundary_conditions = [TheoryBoundary(**b) for b in data.get('boundary_conditions', [])]
        
        # Handle level enum
        level = data.get('level', 'theory')
        if isinstance(level, str):
            level = TheoryLevel(level)
        
        # Handle replication_status enum
        replication_status = data.get('replication_status', 'moderate')
        if isinstance(replication_status, str):
            replication_status = ReplicationStatus(replication_status)
        
        return cls(
            theory_id=data['theory_id'],
            name=data['name'],
            aliases=data.get('aliases', []),
            originators=originators,
            year_introduced=data.get('year_introduced'),
            domain=data.get('domain', []),
            scope_description=data.get('scope_description'),
            level=level,
            core_claims=core_claims,
            assumptions=assumptions,
            boundary_conditions=boundary_conditions,
            overall_confidence=data.get('overall_confidence', 0.5),
            confidence_rationale=data.get('confidence_rationale'),
            quantitative_precision=data.get('quantitative_precision', 'low'),
            parent_theories=data.get('parent_theories', []),
            child_theories=data.get('child_theories', []),
            compatible_theories=data.get('compatible_theories', []),
            competing_theories=data.get('competing_theories', []),
            replication_status=replication_status,
            extraction_source=data.get('extraction_source'),
            extracted_by=data.get('extracted_by'),
            version=data.get('version', 1),
            created_at=data.get('created_at'),
            updated_at=data.get('updated_at'),
        )


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def generate_theory_id(name: str) -> str:
    """Generate a theory ID from name."""
    # Convert to snake_case
    clean = name.lower()
    clean = clean.replace(' ', '_')
    clean = clean.replace('-', '_')
    clean = ''.join(c for c in clean if c.isalnum() or c == '_')
    return f"theory:{clean}"


def generate_prediction_id(theory_id: str, index: int) -> str:
    """Generate a prediction ID."""
    theory_short = theory_id.replace('theory:', '')
    return f"pred:{theory_short}:{index:03d}"


def generate_claim_id(theory_id: str, index: int) -> str:
    """Generate a claim ID."""
    theory_short = theory_id.replace('theory:', '')
    return f"claim:{theory_short}:{index:02d}"


def compute_derivation_confidence(chain: List[DerivationStep], base_confidence: float = 0.9) -> float:
    """
    Compute confidence in a derived prediction based on chain length and step types.
    
    Each step reduces confidence multiplicatively:
    - Deductive: 0.95
    - Inductive: 0.85
    - Analogical: 0.75
    """
    step_factors = {
        'deductive': 0.95,
        'inductive': 0.85,
        'analogical': 0.75,
        'default': 0.80,
    }
    
    confidence = base_confidence
    for step in chain:
        factor = step_factors.get(step.inference_type, step_factors['default'])
        confidence *= factor
    
    return round(confidence, 3)
